version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5431:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env.dev
    networks:
      - backend

  web_app:
    build: .
    networks:
      - backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
#      - static_volume:/usr/src/web_app/staticfiles/
      - .:/usr/src/web_app/ # dev
    ports:
      - 8000:8000
    env_file:
      - .env.dev
    depends_on:
      - db

networks:
  backend:

volumes:
  postgres_data:
#  static_volume:

