version: '3.9'

services:
  db:
    image: postgres:14-alpine
    ports:
      - '5431:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - .env

volumes:
  postgres_data:

