# Generated by Django 4.1.7 on 2023-02-16 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='currency',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
