# Generated by Django 4.1.7 on 2023-02-16 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_item_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128),
        ),
    ]
