# Generated by Django 4.1.7 on 2023-02-17 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_alter_order_currency'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название'),
        ),
    ]
